# Generated by Django 3.2.12 on 2022-02-23 15:49

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='certificate', verbose_name='تصوير')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ شروع')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ پايان')),
                ('describtion_fa', models.TextField(blank=True, null=True, verbose_name=' توضيحات در سايت فارسي ')),
                ('describtion_en', models.TextField(blank=True, null=True, verbose_name=' توضيحات در سايت انگليسي ')),
                ('degree_fa', models.IntegerField(choices=[(1, 'زير ديپلم'), (2, 'ديپلم'), (3, 'كارشناسي'), (4, 'كارشناسي ارشد'), (5, 'دكترا'), (6, 'فوق دكترا')], default=3, verbose_name=' مدرك در سايت فارسي ')),
                ('degree_en', models.IntegerField(choices=[(1, 'High School'), (2, 'Diploma'), (3, 'BA/BSc'), (4, 'MA/MSc'), (5, 'PhD'), (6, 'Post Doctoral')], default=3, verbose_name=' مدرك در سايت انگليسي ')),
                ('gpa_fa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='معدل در سايت فارسي ')),
                ('gpa_en', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name=' معدل در سايت انگليسي ')),
                ('course_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='رشته تحصيلي در سايت فارسي ')),
                ('course_en', models.CharField(blank=True, max_length=200, null=True, verbose_name=' رشته تحصيلي در سايت انگليسي ')),
                ('university_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='دانشگاه محل تحصيل در سايت فارسي ')),
                ('university_en', models.CharField(blank=True, max_length=200, null=True, verbose_name=' دانشگاه محل تحصيل در سايت انگليسي ')),
                ('city_university_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر دانشگاه محل تحصيل در سايت فارسي ')),
                ('city_university_en', models.CharField(blank=True, max_length=50, null=True, verbose_name=' شهر دانشگاه محل تحصيل در سايت انگليسي ')),
                ('country_university_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='كشور دانشگاه محل تحصيل در سايت فارسي ')),
                ('country_university_en', models.CharField(blank=True, max_length=50, null=True, verbose_name=' كشور دانشگاه محل تحصيل در سايت انگليسي ')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'سابقه تحصيل',
                'verbose_name_plural': 'سوابق تحصيلي',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='certificate', verbose_name='تصوير')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ دريافت')),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان مدرك در سايت فارسي ')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان مدرك در سايت انگليسي ')),
                ('location_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name=' دريافتي از سازمان , دانشگاه,... در سايت فارسي ')),
                ('location_en', models.CharField(blank=True, max_length=200, null=True, verbose_name=' دريافتي از سازمان , دانشگاه,... در سايت انگليسي ')),
                ('verify_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='لينك اعتبار سنجي')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غيرفعال')),
            ],
            options={
                'verbose_name': 'سرتيفيكت',
                'verbose_name_plural': 'سرتيفيكيت ها',
            },
        ),
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ و زمان ارسال')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگي')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پيام')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ايميل')),
                ('message', models.TextField(verbose_name='پيام ارسالي')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس ها ',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=120, verbose_name=' عنوان در سايت فارسي ')),
                ('title_en', models.CharField(max_length=120, verbose_name=' عنوان در سايت انگليسي ')),
                ('active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'علاقه مندي',
                'verbose_name_plural': 'علاقه مندي ها',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان شغل در سايت فارسي ')),
                ('job_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان شغل در سايت انگليسي ')),
                ('company_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='كمپاني در سايت فارسي ')),
                ('company_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='كمپاني در سايت انگليسي ')),
                ('city_company_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر كمپاني در سايت فارسي ')),
                ('city_company_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر كمپاني در سايت انگليسي ')),
                ('country_company_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='كشور كمپاني در سايت فارسي ')),
                ('country_company_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='كشور كمپاني در سايت انگليسي ')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ شروع')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ پايان')),
                ('describtion_fa', models.TextField(blank=True, null=True, verbose_name='توضيحات در سايت فارسي ')),
                ('describtion_en', models.TextField(blank=True, null=True, verbose_name='توضيحات در سايت انگليسي ')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'سابقه شغل',
                'verbose_name_plural': 'سوابق شغلي',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان پروژه در سايت فارسي ')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان پروژه در سايت انگليسي ')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لينك پروژه')),
                ('file_project', models.FileField(blank=True, null=True, upload_to='project', verbose_name='فايل پروژه')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='project', verbose_name='كاور پروژه')),
                ('describtion_fa', models.TextField(blank=True, null=True, verbose_name='توضيحات پروژه در سايت فارسي ')),
                ('describtion_en', models.TextField(blank=True, null=True, verbose_name='توضيحات پروژه در سايت انگليسي ')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پرتفوليو',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتشار')),
                ('title_fa', models.TextField(blank=True, null=True, verbose_name='عنوان مقاله در سايت فارسي ')),
                ('title_en', models.TextField(blank=True, null=True, verbose_name='عنوان مقاله در سايت انگليسي ')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لينك')),
                ('status_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='وضعيت مقاله در سايت فارسي ')),
                ('status_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='وضعيت مقاله در سايت انگليسي ')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': ' مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(blank=True, max_length=20, null=True, verbose_name=' عنوان مهارت در سايت فارسي ')),
                ('name_en', models.CharField(blank=True, max_length=20, null=True, verbose_name=' عنوان مهارت در سايت انگليسي ')),
                ('score', models.IntegerField(blank=True, default=80, null=True, verbose_name='امتياز')),
                ('is_key_skill', models.BooleanField(default=True, verbose_name='فعال/غيرفعال')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='  نام و نام خانوادگي در سايت فارسي ')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='  نام و نام خانوادگي در سايت انگليسي ')),
                ('role_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان سمت شغلي در سايت فارسي ')),
                ('role_en', models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان سمت شغلي در سايت انگليسي ')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ايميل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('web_site', models.CharField(blank=True, max_length=200, null=True, verbose_name=' وب سايت')),
                ('describtion_fa', models.TextField(blank=True, null=True, verbose_name=' توضيحات در سايت فارسي ')),
                ('describtion_en', models.TextField(blank=True, null=True, verbose_name='  توضيحات در سايت انگليسي ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غيرفعال')),
            ],
            options={
                'verbose_name': 'مرجع',
                'verbose_name_plural': 'مراجع',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name_fa', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام در سايت فارسي ')),
                ('first_name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name=' نام در سايت انگليسي ')),
                ('last_name_fa', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام خانوادگي در سايت فارسي ')),
                ('last_name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name=' نام خانوادگي در سايت انگليسي ')),
                ('avatar', models.ImageField(blank=True, default='avatar/no-img.png', null=True, upload_to='avatar', verbose_name='تصوير')),
                ('title_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان تخصص در سايت فارسي ')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان تخصص در سايت انگليسي ')),
                ('birthday', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 23, 15, 49, 1, 315438, tzinfo=utc), null=True, verbose_name='تاريخ تولد')),
                ('bio_fa', models.TextField(blank=True, null=True, verbose_name='  توضيحات درباره من در سايت فارسي ')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name=' توضيحات مختصر درباره من در سايت انگليسي ')),
                ('compeltebio_fa', models.TextField(blank=True, null=True, verbose_name=' توضيحات جامع تر درباره من در سايت فارسي ')),
                ('compeltebio_en', models.TextField(blank=True, null=True, verbose_name=' توضيحات جامع تر درباره من در سايت انگليسي ')),
                ('cv_fa', models.FileField(blank=True, default='avatar/no-img.png', null=True, upload_to='cv', verbose_name=' فايل رزومه براي سايت فارسي ')),
                ('cv_en', models.FileField(blank=True, default='avatar/no-img.png', null=True, upload_to='cv', verbose_name=' فايل رزومه براي سايت انگليسي ')),
                ('last_degree_fa', models.IntegerField(choices=[(1, 'زير ديپلم'), (2, 'ديپلم'), (3, 'كارشناسي'), (4, 'كارشناسي ارشد'), (5, 'دكترا'), (6, 'فوق دكترا')], default=3, verbose_name='آخرين مدرك در سايت فارسي ')),
                ('last_degree_en', models.IntegerField(choices=[(1, 'High School'), (2, 'Diploma'), (3, 'BA/BSc'), (4, 'MA/MSc'), (5, 'PhD'), (6, 'Post Doctoral')], default=3, verbose_name=' آخرين مدرك در سايت انگليسي ')),
                ('course_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name=' رشته تحصيلي در سايت فارسي ')),
                ('course_en', models.CharField(blank=True, max_length=200, null=True, verbose_name=' رشته تحصيلي در سايت انگليسي ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('city_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name=' شهر محل زندگي در سايت فارسي ')),
                ('city_en', models.CharField(blank=True, max_length=50, null=True, verbose_name=' شهر محل زندگي در سايت انگليسي ')),
                ('country_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name=' كشور محل زندگي در سايت فارسي ')),
                ('country_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='كشور محل زندگي در سايت انگليسي ')),
                ('freelancer', models.BooleanField(default=True, verbose_name='امكان فريلنسري')),
                ('github', models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم گيت هاب')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم اينستاگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='  شماره واتس اپ')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم تلگرام')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم توييتر')),
                ('youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name=' كانال يوتوب')),
                ('skype', models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم اسكايپ')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم لينكدين')),
                ('googlescholar', models.CharField(blank=True, max_length=100, null=True, verbose_name=' يوزرنيم گوگل اسكولار')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('skills', models.ManyToManyField(blank=True, to='personalinfo.Skill', verbose_name='مهارت ها')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'پروفايل',
                'verbose_name_plural': 'پروفايل كاربري',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
