# Generated by Django 3.2.12 on 2022-02-24 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='file_project',
        ),
        migrations.RemoveField(
            model_name='user',
            name='compeltebio_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='compeltebio_fa',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name=' توضيحات  درباره من در سايت انگليسي '),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 24, 18, 49, 4, 607507, tzinfo=utc), null=True, verbose_name='تاريخ تولد'),
        ),
    ]
